// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd5XemZ04uAxGD4YvECTyd6snvTG5WFss',
    appId: '1:337241698114:web:6d4091bf23f643d211a2db',
    messagingSenderId: '337241698114',
    projectId: 'easyreturns-1dd5a',
    authDomain: 'easyreturns-1dd5a.firebaseapp.com',
    storageBucket: 'easyreturns-1dd5a.appspot.com',
    measurementId: 'G-H9C0VHVGGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYa7EFjoANJgrfy9ypCehoUSBbaG4BGiM',
    appId: '1:337241698114:android:863e07d7f216cc4611a2db',
    messagingSenderId: '337241698114',
    projectId: 'easyreturns-1dd5a',
    storageBucket: 'easyreturns-1dd5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvH6Jl1D5bA-PtX7l5nbnZEfrMgyrykKE',
    appId: '1:337241698114:ios:812b143081de571411a2db',
    messagingSenderId: '337241698114',
    projectId: 'easyreturns-1dd5a',
    storageBucket: 'easyreturns-1dd5a.appspot.com',
    iosClientId: '337241698114-9l1uipi4354442jcl6s05fip7pb3nqk0.apps.googleusercontent.com',
    iosBundleId: 'com.matias.easyreturns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvH6Jl1D5bA-PtX7l5nbnZEfrMgyrykKE',
    appId: '1:337241698114:ios:cba67e18f6630e0a11a2db',
    messagingSenderId: '337241698114',
    projectId: 'easyreturns-1dd5a',
    storageBucket: 'easyreturns-1dd5a.appspot.com',
    iosClientId: '337241698114-il6tpbbf11ikmpqdu7imec109mu9ovp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyreturns',
  );
}
